### ISSUE TITLE
All downloads except nested JSON return HTTP 500 Internal Server Error

### ISSUE THREAD

**Issue by ifokkema** [bzrudski/antnuptracker-server#3]
Hi,
This is a very interesting project!
You may already be aware of this, but all download links from https://www.antnuptialflights.com/download/ return an HTTP 500 Internal Server Error, except the nested JSON link. I did notice that the URL of the working link is different from the URL of the broken links, but I couldn't compose working URLs for other formats.

**Comment by bzrudski** [comment]
Thanks for posting the issue. The issue involves the serialization for the download. Just pushed the fix to git.
